### ISSUE TITLE
Could not resolve dependency error

### ISSUE THREAD

**Issue by poveroenricco** [donalmurtagh/runtime-datasources#5]
During dependencies installation, Grails 3 app can not resolve `compile "org.grails.plugins:runtime-datasources:0.2"` because plugin is missing in [Grails plugins repository](http://repo.grails.org/grails/core/org/grails/plugins/).

**Comment by domurtag** [comment]
The version to be used for a Grails 3 app is `0.2-grails3`
https://github.com/domurtag/runtime-datasources/blob/grails3/build.gradle#L19

**Comment by enron92** [comment]
Also `0.2-grails3` is missing.

**Comment by domurtag** [comment]
[`0.2-grails3` is here](https://bintray.com/domurtag/plugins/domurtag.plugins:runtime-datasources)
